# Generated by Django 3.1.4 on 2020-12-12 06:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPost',
            new_name='ProjectPost',
        ),
    ]
