# Generated by Django 3.1.4 on 2020-12-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201215_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='projectpost',
            old_name='body',
            new_name='builtwith',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='project_status',
            field=models.ManyToManyField(blank=True, to='base.ProjectStatus'),
        ),
    ]
