# Generated by Django 3.1.4 on 2020-12-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201217_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project Statuses'},
        ),
    ]
