# Generated by Django 3.1.4 on 2020-12-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201217_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='created',
        ),
    ]
