# Generated by Django 3.1.4 on 2020-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_projectpost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='project_status',
            field=models.ManyToManyField(to='base.ProjectStatus'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='sub_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='tags',
            field=models.ManyToManyField(to='base.Tag'),
        ),
    ]
