# Generated by Django 3.1.4 on 2020-12-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201219_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='sub_heading',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
