# Generated by Django 3.1.4 on 2020-12-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201219_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='github_link',
            field=models.URLField(null=True),
        ),
    ]
