# Generated by Django 3.1.4 on 2020-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_projectpost_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
