# Generated by Django 3.1.4 on 2020-12-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20201219_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='builtwith',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
