# Generated by Django 3.1.4 on 2020-12-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20201222_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpostimage',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='projectpostimage',
            name='caption',
            field=models.CharField(default='Picture', max_length=200),
        ),
    ]
