# Generated by Django 3.1.4 on 2020-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201227_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='sub_heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
