# Generated by Django 3.1.4 on 2021-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210129_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
